#ifndef _NF_COMM_H_
#define _NF_COMM_H_
#include "../../../slib/src/slib.h"
USING_NAMESPACE_S



#define __ECgiCmdType_c2sReq_RedEnvelope_GiverCreateSession 1001
#define __ECgiCmdType_c2sReq_RedEnvelope_GiverDeleteSession 1002
#define __ECgiCmdType_c2sReq_RedEnvelope_GiverUpdateSession 1003
#define __ECgiCmdType_c2sReq_RedEnvelope_GiverReportScanResult 1004
#define __ECgiCmdType_c2sReq_RedEnvelope_ReceiverCreateSession 1005
#define __ECgiCmdType_c2sReq_RedEnvelope_ReceiverDeleteSession 1006
#define __ECgiCmdType_c2sReq_RedEnvelope_ReceiverUpdateSession 1007
#define __ECgiCmdType_c2sReq_RedEnvelope_ReceiverReportScanResult 1008
#define __ECgiCmdType_c2sReq_RedEnvelope_ReportStatisticZishi 1101
#define __ECgiCmdType_c2sReq_AddFriend_ReportUserInfo 1201
#define __ECgiCmdType_c2sReq_AddFriend_QueryUserInfo 1202

#define __ECgiCmdType_s2cResp_RedEnvelope_GiverCreateSession 2001
#define __ECgiCmdType_s2cResp_RedEnvelope_GiverDeleteSession 2002
#define __ECgiCmdType_s2cResp_RedEnvelope_GiverUpdateSession 2003
#define __ECgiCmdType_s2cResp_RedEnvelope_GiverReportScanResult 2004
#define __ECgiCmdType_s2cResp_RedEnvelope_ReceiverCreateSession 2005
#define __ECgiCmdType_s2cResp_RedEnvelope_ReceiverDeleteSession 2006
#define __ECgiCmdType_s2cResp_RedEnvelope_ReceiverUpdateSession 2007
#define __ECgiCmdType_s2cResp_RedEnvelope_ReceiverReportScanResult 2008
#define __ECgiCmdType_s2cResp_RedEnvelope_ReportStatisticZishi 2101
#define __ECgiCmdType_s2cResp_AddFriend_ReportUserInfo 2201
#define __ECgiCmdType_s2cResp_AddFriend_QueryUserInfo 2202


#define __ECgiCmdType_s2cPush_RedEnvelope_MatchResult 3001
#define __ECgiCmdType_s2cPush_AddFriend_MatchResult 3101



#endif // !_NF_COMM_H_
